# EduPro Course Demand & Revenue Forecasting - Business Insights
This notebook summarizes key findings, pricing suggestions, new category expansion plans, and teacher hiring insights based on our EDA and models.

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

# Load datasets
course_level = pd.read_csv('../data/processed/course_level_dataset.csv')

### 1. Pricing Strategy Insights

In [2]:
pricing_summary = course_level.groupby('PriceBand', observed=False).agg(
    CourseCount=('CourseID', 'count'),
    AvgEnrollments=('TotalEnrollments', 'mean'),
    AvgRevenue=('TotalRevenue', 'mean')
).reset_index()
display(pricing_summary)

  PriceBand  CourseCount  AvgEnrollments  AvgRevenue
0      Free           38      168.500000       0.000
1      High            5      164.800000   74829.562
2       Low            7      168.428571   11332.650
3    Medium           10      159.400000   45784.711

### 2. Category Performance Insights

In [3]:
category_summary = course_level.groupby('CourseCategory').agg(
    CourseCount=('CourseID', 'count'),
    AvgEnrollments=('TotalEnrollments', 'mean'),
    TotalRevenue=('TotalRevenue', 'sum')
).sort_values(by='TotalRevenue', ascending=False)
display(category_summary)

                         CourseCount  AvgEnrollments  TotalRevenue
CourseCategory
Artificial Intelligence            5           165.8     202750.67
Business                           5           166.6     181527.58
Project Management                 5           165.8     169103.21
Programming                        5           161.2      77453.92
Data Science                       5           183.2      77052.32
Cybersecurity                      5           163.8      59139.00
Digital Marketing                  5           161.6      56261.32
Design                             5           165.4      43113.72
Finance                            5           172.8      28106.20
Web Development                    5           168.8      16682.15
Machine Learning                   5           163.8        133.38
Marketing                          5           161.2          0.00

### 3. Instructor Insights

In [4]:
experience_summary = course_level.groupby('ExperienceBucket', observed=False).agg(
    AvgRating=('TeacherRating', 'mean'),
    AvgEnrollments=('TotalEnrollments', 'mean'),
    TotalRevenue=('TotalRevenue', 'sum')
)
display(experience_summary)

                  AvgRating  AvgEnrollments  TotalRevenue
ExperienceBucket
0-2 years          3.110000      167.000000          0.00
10+                4.799818      167.054545     892158.03
3-5 years          1.790000      178.000000          0.00
6-10 years         3.770000      155.666667      19165.44